export const CourseActionTypes = {
   ADD_DEADLINE: 'ADD_DEADLINE',
   REMOVE_DEADLINE: 'REMOVE_DEADLINE',
   TOGGLE_SORT : 'TOGGLE_SORT',
   SORT_DEADLINE: 'SORT_DEADLINE',
   TOGGLE_EDIT: 'TOGGLE_EDIT',
}