export const CourseActionTypes = {
   ADD_DEADLINE: 'ADD_DEADLINE',
   ADD_DEADLINE_SUCCESS: 'ADD_DEADLINE_SUCCESS',
   ADD_DEADLINE_FAILURE: 'ADD_DEADLINE_FAILURE',

   REMOVE_DEADLINE: 'REMOVE_DEADLINE',
   REMOVE_DEADLINE_SUCCESS: 'REMOVE_DEADLINE_SUCCESS',
   REMOVE_DEADLINE_FAILURE: 'REMOVE_DEADLINE_FAILURE',

   REMOVE_DEADLINE_ON_SIGN_OUT: 'REMOVE_DEADLINE_ON_SIGN_OUT',

   EDIT_DEADLINE: 'EDIT_DEADLINE',
   EDIT_DEADLINE_SUCCESS: 'EDIT_DEADLINE_SUCCESS',
   EDIT_DEADLINE_FAILURE: 'EDIT_DEADLINE_FAILURE',

   SORT_DEADLINE: 'SORT_DEADLINE',
   TOGGLE_SORT : 'TOGGLE_SORT',
   TOGGLE_EDIT: 'TOGGLE_EDIT',
   SORT_DEADLINE_DND: 'SORT_DEADLINE_DND',

   FETCH_DEADLINES_DATA: 'FETCH_DEADLINES_DATA',
   FETCH_DEADLINES_DATA_SUCCESS: 'FETCH_DEADLINES_DATA_SUCCESS',
   FETCH_DEADLINES_DATA_FAILURE: 'FETCH_DEADLINES_DATA_FAILURE',
}