export const CourseActionTypes = {
   ADD_DEADLINE: 'ADD_DEADLINE',
   REMOVE_DEADLINE: 'REMOVE_DEADLINE',
   EDIT_DEADLINE: 'EDIT_DEADLINE',
   SORT_DEADLINE: 'SORT_DEADLINE',
   TOGGLE_SORT : 'TOGGLE_SORT',
   TOGGLE_EDIT: 'TOGGLE_EDIT',
   TOGGLE_SETTINGS: 'TOGGLE_SETTINGS',
   SORT_DEADLINE_DND: 'SORT_DEADLINE_DND',
   EDIT_SETTINGS: 'EDIT_SETTINGS',
   TOGGLE_DARK_MODE: 'TOGGLE_DARK_MODE',
}